// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCLf5zg9fuhES_U48CiCoxdQXhQTSUi0',
    appId: '1:698795997498:web:1f818e6ef86e1eca77b803',
    messagingSenderId: '698795997498',
    projectId: 'smart-health-care-app-67335',
    authDomain: 'smart-health-care-app-67335.firebaseapp.com',
    storageBucket: 'smart-health-care-app-67335.appspot.com',
    measurementId: 'G-1634FF5NKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXEAeVH48drseKA6kjJZTI9sDC1kr5qw',
    appId: '1:698795997498:android:d2ad73ec41725feb77b803',
    messagingSenderId: '698795997498',
    projectId: 'smart-health-care-app-67335',
    storageBucket: 'smart-health-care-app-67335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3fO_8UFXEy8eLpK691FTSabpp8vDgpWw',
    appId: '1:698795997498:ios:d71349538c671cd377b803',
    messagingSenderId: '698795997498',
    projectId: 'smart-health-care-app-67335',
    storageBucket: 'smart-health-care-app-67335.appspot.com',
    iosBundleId: 'com.example.extraViews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3fO_8UFXEy8eLpK691FTSabpp8vDgpWw',
    appId: '1:698795997498:ios:d71349538c671cd377b803',
    messagingSenderId: '698795997498',
    projectId: 'smart-health-care-app-67335',
    storageBucket: 'smart-health-care-app-67335.appspot.com',
    iosBundleId: 'com.example.extraViews',
  );
}
